# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4ef544d91e49c9acd64bbf0e44eb9c874314f520678be02dea231204b25ca4b67ad5cb961442c820666f7832e10f0fd76bb961f62fc6bf7017ca7d2ad8f3dbb9

test:
  secret_key_base: 0a752a0bf7e19d47cf7da622528360af1f8bda3e8b47c918f898b470800d7382c3135d1d1cc65d1ab9f7e826f2a3f1fc5face08ac7ff6972ddb60f1f8e434e92

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
